version: '3.4'

x-base-app: &base-app
  image: beabee/beabee:API_VERSION
  env_file:
    - stack.env
  networks:
    - internal
    - db-network
  logging:
    driver: gelf
    options:
      gelf-address: "udp://127.0.0.1:12201"
      env: stack,service
  environment:
    stack: ${COMPOSE_PROJECT_NAME}

x-app: &app
  <<: *base-app
  restart: unless-stopped
  depends_on:
    migration:
      condition: service_completed_successfully

services:
  migration:
    <<: *base-app
    command: 'npm run typeorm migration:run'
    environment:
      service: migration

  app:
    <<: *app
    environment:
      service: app

  api_app:
    <<: *app
    command: 'node built/api/app'
    environment:
      service: api_app

  webhook_app:
    <<: *app
    command: 'node built/webhooks/app'
    environment:
      service: webhook_app

  cron:
    <<: *app
    user: root
    command: 'crond -f -d 7'
    init: true
    environment:
      service: cron

  img_upload_app:
    image: hascheksolutions/pictshare:72394f17
    restart: unless-stopped
    environment:
      CONTENTCONTROLLERS: IMAGE,TEXT
    init: true
    volumes:
      - upload_data:/var/www/data
    networks:
      - internal

  router:
    image: beabee/router:API_VERSION
    restart: unless-stopped
    networks:
      - internal

  run:
    <<: *app
    profiles:
      - tools
    logging:
      driver: none

  frontend:
    image: beabee/frontend:FRONTEND_VERSION
    restart: unless-stopped
    environment:
      APP_BASE_URL: ${BEABEE_AUDIENCE}
      API_BASE_URL: /api/1.0
      CNR_MODE: ${BEABEE_CNR_MODE-}
    networks:
      - internal

  app_router:
    image: beabee/app-router:latest
    restart: unless-stopped
    labels:
      - "traefik.docker.network=traefik-ingress"
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entryPoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${BEABEE_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certResolver=letsencrypt"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
    environment:
      LEGACY_APP_URL: http://router
      LEGACY_APP_COOKIE_DOMAIN: ${BEABEE_COOKIE_DOMAIN}
      FRONTEND_APP_URL: http://frontend
    networks:
      - internal
      - traefik-ingress

networks:
  internal:
    driver: bridge
  db-network:
    external: true
  traefik-ingress:
    external: true

volumes:
  upload_data:
